# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lockr < Formula
  desc "Secure personal vault CLI with interactive fuzzy search"
  homepage "https://github.com/metabot/lockr"
  version "0.1.2"
  license "MIT"

  depends_on "sqlcipher"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/metabot/lockr/releases/download/v0.1.2/lockr_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "a6ea9176a564dd31ecd1a9a45ea311bca9bd17b4aefca34a382efc436cbb5a31"

    def install
      bin.install "lockr"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/metabot/lockr/releases/download/v0.1.2/lockr_0.1.2_Darwin_arm64.tar.gz"
    sha256 "8876617a3cd6347b0ab4ff7ffd2d8b8f2781f0896f73873f605f2cbd4b62e41f"

    def install
      bin.install "lockr"
    end
  end

  test do
    system "#{bin}/lockr", "version"
  end
end
